<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="EPINHYDW0900" failures="0" tests="5" name="com.epam.automation.websevices.test.RestAssuredDemo" time="0.177" errors="1" timestamp="10 Jan 2018 13:30:35 GMT" skipped="4">
  <testcase classname="com.epam.automation.websevices.test.RestAssuredDemo" name="initTest" time="0.177">
    <error message="javax/xml/bind/JAXBException" type="java.lang.NoClassDefFoundError">
      <![CDATA[java.lang.NoClassDefFoundError: javax/xml/bind/JAXBExceptionat io.restassured.config.ObjectMapperConfig.<init>(ObjectMapperConfig.java:49)at io.restassured.config.RestAssuredConfig.<init>(RestAssuredConfig.java:41)at io.restassured.RestAssured.<clinit>(RestAssured.java:420)at com.epam.automation.websevices.test.RestAssuredDemo.initTest(RestAssuredDemo.java:23)at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)at java.base/java.lang.reflect.Method.invoke(Unknown Source)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:451)at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:163)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:105)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBExceptionat java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)at java.base/java.lang.ClassLoader.loadClass(Unknown Source)... 30 more]]>
    </error>
  </testcase> <!-- initTest -->
  <testcase classname="com.epam.automation.websevices.test.RestAssuredDemo" name="checkResponseHeader" time="0.000">
    <skipped/>
  </testcase> <!-- checkResponseHeader -->
  <testcase classname="com.epam.automation.websevices.test.RestAssuredDemo" name="checkResponseHeaderValue" time="0.000">
    <skipped/>
  </testcase> <!-- checkResponseHeaderValue -->
  <testcase classname="com.epam.automation.websevices.test.RestAssuredDemo" name="checkStatusCode" time="0.000">
    <skipped/>
  </testcase> <!-- checkStatusCode -->
  <testcase classname="com.epam.automation.websevices.test.RestAssuredDemo" name="checkBodyLength" time="0.000">
    <skipped/>
  </testcase> <!-- checkBodyLength -->
</testsuite> <!-- com.epam.automation.websevices.test.RestAssuredDemo -->
